// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamTracker.Data;

namespace SteamTracker.Data.Migrations
{
    [DbContext(typeof(SteamContext))]
    [Migration("20190310080401_InitialDatabaseSetup")]
    partial class InitialDatabaseSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SteamTracker.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameForeignKey");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PlayTime");

                    b.HasKey("Id");

                    b.HasIndex("GameForeignKey");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SteamTracker.Data.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameCount");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SteamTracker.Data.Models.Game", b =>
                {
                    b.HasOne("SteamTracker.Data.Models.Player")
                        .WithMany("Games")
                        .HasForeignKey("GameForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
